openapi: 3.0.0
info:
  title: Anime List API
  version: 0.0.1
paths:
  /api/v1/animes:
    get:
      responses:
        "200":
          description: List of all anime
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ERROR"
                  data:
                    type: object
                    properties:
                      name:
                        type: string
                        example: "INTERNAL_SERVER_ERROR"
                      message:
                        type:
                        example: "Something is error"
                      stack:
                        type: string
                        example: "router/animeRouter.js:10"
    post:
      responses:
        "201":
        "400": {}
        "401": {}
        "422": {}
        "500": {}
  /api/v1/animes/{id}:
    get:
      responses:
        "200": {}
    patch:
      responses:
        "200": {}
        "400": {}
        "403": {}
        "404": {}
        "422": {}
    delete:
      responses:
        "204": {}
        "403": {}
        "404": {}
